# -*- coding: utf-8 -*-
"""1111.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fjt7r2vyemt0m_vfTRPh7XSVYpAEvjdf
"""

'''
어떤 정수가 입력되면 %를 붙여 출력하시오.
'''
a=input()
a=int(a)
print(a,'%',sep='')