# -*- coding: utf-8 -*-
"""1115.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fjt7r2vyemt0m_vfTRPh7XSVYpAEvjdf
"""

'''
두 정수의 덧셈의 결과를 출력한다.

두 수는 int 범위를 넘어선 64비트 정수형 값이다.
'''
a,b=input().split(" ")
a=int(a)
b=int(b)
print(a+b)