# -*- coding: utf-8 -*-
"""1127.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fjt7r2vyemt0m_vfTRPh7XSVYpAEvjdf
"""

'''

중간 고사	기말 고사	수행 평가
반영 비율	30%	30%	40%
받은 점수	86	90	85
0.3 × 86 + 0.3 × 90 + 0.4 × 85 = 86.8

 결과를 실수로 출력하되 소수 첫째 자리까지 출력한다.
'''
import numpy as np
i=0
c=[]
while i<3:
  a,b=input().split(" ")
  a=float(a)
  b=float(b)
  i=i+1
  c.append(a*b)

print('{}'.format(np.round(sum(c),1)))