# -*- coding: utf-8 -*-
"""1157.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fjt7r2vyemt0m_vfTRPh7XSVYpAEvjdf
"""

'''
50이상 60이하이면 win을 출력, 그 외에는 lose를 출력하시오.
'''

a=input()
a=float(a)
if 50<=a:
  if a<=60:
    print("win")
  else:
    print("lose")
else:
  print("lose")