# -*- coding: utf-8 -*-
"""1201.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fjt7r2vyemt0m_vfTRPh7XSVYpAEvjdf
"""

'''

정수 하나를 입력받아 양수이면 "양수", 음수이면 "음수", 0이면 0을 출력하시오.
'''
n=input()
n=int(n)
if n==0:
  print("0")
elif n<0:
  print("음수")
else:
  print("양수")