# -*- coding: utf-8 -*-
"""1214.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fjt7r2vyemt0m_vfTRPh7XSVYpAEvjdf
"""

'''
연도와 월이 입력된다.

- 조건 1 : 400의 배수인 해는 모두 윤년이다.
- 조건 2 : 4의 배수인 해들 중 100의 배수가 아닌 해들은 모두 윤년이다.

그 달의 마지막 날이 며칠인지 출력한다.
'''

a,b=input().strip().split(" ")
a=int(a)
b=int(b)
if b==1 or b==3 or b==5 or b==7 or b==8  or b==10 or b==12:
  print("31")
elif b==4 or b==6 or b==9 or b==11:
  print("30")
else:
  if a%400==0:
    print("29")
  elif a%4==0:
    if a%100!=0:
      print('29')
    else:
      print('28')
  else:
    print('28')