# -*- coding: utf-8 -*-
"""1272.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fjt7r2vyemt0m_vfTRPh7XSVYpAEvjdf
"""

'''
1, 10, 2, 20, 3, 30, 4, 40, 5, 50, 6, 60, 7, 70, 8, 80, 9, 90, 10, 100, 11, 110, 12, 120, ...

한 줄에 k, h가 공백으로 분리되어 순서대로 입력된다.
해당하는 금액의 합을 구한다. 
'''
import numpy as np
a,b=input().strip().split(" ")
a=int(a)
b=int(b)
c=[a,b]
d=np.max(c)
k=[]
t=0
for i in range(1,d+1):
  if i%2!=0:
    t=t+1
    k.append(t)
  else:
    k.append(i*5)

print(k[a-1]+k[b-1])