# -*- coding: utf-8 -*-
"""1293.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fjt7r2vyemt0m_vfTRPh7XSVYpAEvjdf
"""

'''
① 첫 번째 줄에 입력 점수의 개수 n이 입력되고, 그 다음 줄에 n개의 점수가 공백으로 구분되어 입력된다.(2≤n≤100)
② 각 점수의 범위는 0 ~ 100점인 정수이다.

 n명의 점수 중 1등과 꼴등의 점수를 공백을 두고 출력한다..
'''
import numpy as np 
a=input()
b=list(map(int,input().strip().split(" ")))
print(np.max(b), np.min(b))