# -*- coding: utf-8 -*-
"""1452.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fjt7r2vyemt0m_vfTRPh7XSVYpAEvjdf
"""

'''
N개의 데이터가 입력되면, 오름차순된 결과를 출력하는 프로그램을 작성하시오. 
'''
a=input()
a=int(a)
b=[]
for i in range(a):
  c=input()
  c=int(c)
  b.append(c)
b=sorted(b)
for i in range(0,len(b)):
  print(b[i])